name: Validate Examples

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Install dependencies
      run: npm ci
    
    - name: Validate all examples
      run: npm run validate:examples
    
    - name: Validate schema
      run: |
        echo "Validating JSON Schema..."
        npx ajv compile -s spec/latest/schema.json
    
    - name: Run linter
      run: npm run lint
      continue-on-error: true
    
    - name: Check for broken symlinks
      run: |
        if [ -L spec/latest ] && [ ! -e spec/latest ]; then
          echo "Error: spec/latest symlink is broken"
          exit 1
        fi
    
    - name: Validate individual examples
      run: |
        echo "Testing individual validations..."
        node validator/cli.js examples/minimal/hello-world-llm.yml
        node validator/cli.js examples/libraries/express-llm.yml
        node validator/cli.js examples/libraries/react-llm.yml
        node validator/cli.js examples/libraries/fastapi-llm.yml
        node validator/cli.js examples/frameworks/superclaude-sdk-llm.yml
    
    - name: Test recursive validation
      run: |
        echo "Testing recursive directory validation..."
        node validator/cli.js . --recursive | grep -E "(Valid|Invalid)" || true
    
    - name: Upload validation results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: validation-errors
        path: |
          *.log
          validation-results.txt